butler:
   #/sps/lsst/users/rbonnetguerrini/pipelines/rc2_subset/SMALL_HSC/  #/sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
  repo: "/sps/lsst/users/rbonnetguerrini/pipelines/rc2_subset/SMALL_HSC/"
  collections: [u/rbonnetguerrini/step8] #run/ssp_ud_cosmos/step5

injection:
  galaxy_fraction: 0.063     
  hostless_fraction: 0.10      # 10% of injections are hostless
  min_injections: 1            # Minimum injections per CCD
  max_injections: null         # No maximum limit (null = None)
  random_seed: 42              # For reproducible results

data_selection:
  band: "r"                    # Filter band
  patch: null                  # All patches (null = None)
  visit_range: null            # All visits (or [min_visit, max_visit])
  detector_range: null         # All detectors (or [min_det, max_det])

output:
  save_csv: true
  output_dir: "catalogs/rc2_subset"
  filename_prefix: "saved/injection_catalogs/45000inj/45000inj"

mag_distribution:
  file: "/sps/lsst/users/rbonnetguerrini/ML4transients/saved/mag_distrib.json"