repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
collection: run/ssp_ud_cosmos/step5_new
injection: false
cutout:
  size: 30
  coadd_science: true
  save: true
  save_features_only: false
  return_data: false
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/data/UDEEP_coadd
lightcurves:
  patches: []
  cache_size: 5
skip_global_index: true
skip_lightcurve_index: true
run_info:
  status: completed
  started: '2025-07-24T14:01:00'
  finished: '2025-11-23T10:44:25.998790'
