collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: true
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
lightcurves:
  cache_size: 5
  patches: []
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/data/UDEEP_coadd_v2
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-11-21T15:16:25.471453'
  started: '2025-07-24T14:01:00'
  status: running
skip_global_index: true
skip_lightcurve_index: true
visits:
- 274
- 276
- 282
- 284
- 286
- 288
- 290
- 292
- 294
- 296
- 298
- 300
- 302
- 306
- 308
