collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: true
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
lightcurves:
  cache_size: 5
  patches: []
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/data/UDEEP_coadd
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-10-28T15:39:14.208444'
  started: '2025-07-24T14:01:00'
  status: running
skip_global_index: true
skip_lightcurve_index: true
visits:
- 1870
- 1872
- 1874
- 1876
- 1878
- 1880
- 1882
- 1886
- 1888
- 1890
- 11688
- 11690
- 11692
- 11694
- 11696
