collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: true
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
lightcurves:
  cache_size: 5
  patches: []
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/data/UDEEP_coadd
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-10-28T15:38:55.549606'
  started: '2025-07-24T14:01:00'
  status: running
skip_global_index: true
skip_lightcurve_index: true
visits:
- 1232
- 1234
- 1236
- 1238
- 1240
- 1242
- 1244
- 1246
- 1248
- 1856
- 1858
- 1860
- 1862
- 1864
- 1868
