collection: run/ssp_ud_cosmos/step5_new
cutout:
  coadd_science: true
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: false
lightcurves:
  cache_size: 5
  patches: []
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/data/UDEEP_coadd
repo: /sps/lsst/groups/transients/HSC/fouchez/RC2_repo/butler.yaml
run_info:
  finished: '2025-10-28T15:38:23.448869'
  started: '2025-07-24T14:01:00'
  status: running
skip_global_index: true
skip_lightcurve_index: true
visits:
- 1166
- 1168
- 1170
- 1172
- 1174
- 1176
- 1178
- 1180
- 1182
- 1184
- 1186
- 1188
- 1190
- 1192
- 1194
