collection: u/rbonnetguerrini/injected_step6
cutout:
  coadd_science: true
  return_data: false
  save: true
  save_features_only: false
  size: 30
injection: true
path: /sps/lsst/groups/transients/HSC/fouchez/raphael/data/rc2_coadd
repo: /sps/lsst/users/bsanchez/hsc_processing/pgrc2subset_2/butler.yaml
run_info:
  finished: '2025-11-05T15:25:26.845963'
  started: '2025-07-24T14:01:00'
  status: completed
skip_global_index: true
skip_lightcurve_index: true
visits:
- 322
- 346
- 358
- 1178
- 1184
- 1204
- 1206
- 1214
- 1220
- 1242
- 1248
- 11690
- 11694
- 11696
- 11698
- 11704
- 11710
- 11724
- 11738
- 11740
